fest/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings

from fest.views import score, rateMe, home, result_action, ItemListView, ItemDetailScoreView, ItemDetailView, confirm_rating, save_score, SpecialAwardListView
from django.contrib import admin
from django.contrib.auth.views import logout, password_change, password_change_done
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', home, name='home'),
    url(r'^score/$', score, name='items'),
    url(r'^awards/$', SpecialAwardListView.as_view(), name='awards'),
    url(r'^report/$', ItemListView.as_view(), name='item_report'),
    url(r'^report/(?P<pk>\d+)$', ItemDetailView.as_view(), name='item_rating_report'),
    url(r'^score/(?P<pk>\d+)$', ItemDetailScoreView.as_view(), name='item_jury_scoring'),
    url(r'^score/save$', save_score, name='save_score'),
    url(r'^resultaction/$', result_action, name='resultaction'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^rate/$', rateMe, name='rating'),
    url(r'^rating/confirm$', confirm_rating, name='confirm_rating'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^password/$', password_change,{'template_name':'password_change_form.html'}, name='change_password'),
    #url(r'^password/$', password_change, name='change_password'),
    url(r'^password/done$', password_change_done,{'template_name':'password_change_done.html'}, name='password_change_done'),
)

if settings.DEBUG and settings.MEDIA_ROOT:
    urlpatterns += patterns('',
        (r'^files/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))
    urlpatterns += static(settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

fest/models.py
from django.db import models
from django.contrib.auth.models import User, Group

class Item(models.Model):
    UP = 'U'
    HS = 'H'
    HSS = 'S'
    VHSS = 'V'
    HSS_VHSS = 'W'
    CATEGORY_CHOICES = ((UP, 'UP'),
        (HS, 'HS'),
        (HSS, 'HSS'),
        (VHSS, 'VHSS'),
        (HSS_VHSS, 'HSS/VHSS'))
    name = models.CharField(max_length=64)
    category = models.CharField(max_length=1, choices=CATEGORY_CHOICES)
    is_student_ratable = models.BooleanField(default=False)
    is_result_published = models.BooleanField(default=False)
    is_confirmed = models.BooleanField(default=False)

    def __unicode__(self):
        return '%s %s' % (self.get_category_display(), self.name)

class Student(models.Model):
    user = models.OneToOneField(User)
    school = models.CharField(max_length=64)
    schoolcode = models.CharField(max_length=8)
    std = models.IntegerField(null=True, blank=True, default=0)
    is_rating_confirmed = models.BooleanField(default=False)

    def __unicode__(self):
        return "%s@%s" % (self.user.get_full_name(), self.schoolcode)

class Participant(models.Model):
    item = models.ForeignKey(Item)
    student = models.ForeignKey(Student)
    code = models.CharField(max_length=32)

    def __unicode__(self):
        return "%s #%s" % (self.item, self.code)
    class Meta:
        unique_together = (('item', 'code'), ('student', 'code'))

class Jury(models.Model):
    user = models.OneToOneField(User)
    bio = models.TextField(blank=True, null=True)
    items = models.ManyToManyField(Item)

    def __unicode__(self):
        return "%s" % (self.user.username)

class Score(models.Model):
    participant = models.ForeignKey(Participant)
    scored_by = models.ForeignKey(User)
    mark = models.IntegerField()
    is_student = models.BooleanField(default=True)
    class Meta:
        unique_together = ('scored_by', 'participant')

class JuryScore(Score):
    class Meta:
        proxy = True

    def __init__(self, *args, **kwargs):
        super(Score, self).__init__(*args, **kwargs)
        self.is_student = False

class Result(models.Model):
    participant = models.ForeignKey(Participant)
    score = models.FloatField()
    student_score = models.FloatField(default=0)
    experts_score = models.FloatField(default=0)

class SpecialAward(models.Model):
    participant = models.ForeignKey(Participant)
    title = models.CharField(max_length=64)
    comment = models.TextField(null=True, blank=True)

    def __unicode__(self):
        return "%s-%s" % (self.title, self.participant)

templates/base.html
{% load static from staticfiles %}
{% load url from future %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Animation Competition</title>

    <!-- Bootstrap -->
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
    {% block css %}
    {% endblock %}

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js' %}"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js' %}"></script>
    <![endif]-->
  </head>
  <body>
    <div class="wrapper">
      <header class="heading">
        <div class="container">
          <nav class="navbar">
            <ul class="center-block nav nav-pills-1">
              <li class="active"><a href="/">Home</a></li>
              {% if user.is_authenticated %}
                {% for group in user.groups.all %}
                    {% if group.name == 'Jury' %}
                    <li><a href="/report">Score</a></li>
                    {% elif group.name == 'Admin' %}
                    <li><a href="/report">Score</a></li>
                    {% elif group.name == 'Student' %}
                    <li><a href="/score">Score</a></li>
                    {% endif %}
                {% endfor %}
                <li><a href="{% url 'change_password' %}">Change Password</a></li>
                <li><a href="{% url 'logout' %}">Logout</a></li>
              {% endif %}
            </ul>
          </nav>
        </div>
      </header>

      {% if messages %}
        {% for message in messages %}
        <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endfor %}
      {% endif %}

      {% block content %}
      {% endblock %}

      <footer class="page-footer">
        <div class="container">
          <div class="col-sm-3"><h3>Animation Competition</h3><p>IT@School Wayanad</p></div>
          <ul class="list-unstyled">
            <li class='col-sm-3'>
            <h5><strong>Links</strong></h5>
              <ul class="list-unstyled">
                <li><a href="#">Home</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Contact</a></li>
              </ul>
            </li>
            <li class='col-sm-3'>
            <h5><strong>Social Networking</strong></h5>
              <ul class="list-unstyled">
                <li><a href="#">Facebook</a></li>
                <li><a href="#">Twitter</a></li>
              </ul>
            </li>
            <li class='col-sm-3'>
            <h5><strong>Team</strong></h5>
              <ul class="list-unstyled">
                <li><a href="#">#</a></li>
              </ul>
            </li>
          </ul>
        </div>
        <div class="row text-center">&copy;2014 c4s</dev>
      </footer>
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    {% block js %}
    {% endblock %}
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block content %}
{% if not user.is_authenticated %}
  <div class="container">
<div class="page-header">
<h2 class='text-center'>Animation Competition</h2>
</div>
</div>
<section class="main" role="main">
  <div class="container">
    <span class="col-md-1">&nbsp;</span>
    <div class="col-md-5">
      <blockquote class="blockquote-reverse">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
        <footer>Someone famous in <cite title="Source Title">Source Title</cite></footer>
      </blockquote>
    </div>

    <div class="col-md-5">
      <div class="login">
        <form action="" method="post">
          {% csrf_token %}
          <div class="input-group">
            <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
            <input type="text" class="form-control" placeholder="Username" name="username" id="id_username">
          </div>
          <br>
          <div class="input-group">
            <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
            <input type="password" class="form-control" placeholder="Password" name="password" id="id_password">
          </div>
          <br>
          <button class="btn btn-primary" value="Login">Login</button>
          <button class="btn btn-secondary" value="Sign Up">Sign Up</button>
        </form>
      </div>
    </div>
    <span class="col-md-1">&nbsp;</span>

  </div>
</section>
{% endif %}

<section class="">
  <div class="container">
    {% for item in results %}
      <h2>{{ item.item.get_category_display }} {{ item.item.name }}</h2>
      <table class="table">
        <tr>
          <th>Code</th>
          <th>Student</th>
          <th>School</th>
          <th>Rank</th>
        </tr>
        {% for r in item.common_result %}
        <tr>
          <td>{{ r.result.participant.code }}</td>
          <td>{{ r.result.participant.student.user.get_full_name }}</td>
          <td>{{ r.result.participant.student.school }}</td>
          <td>{{ r.rank }}</td>
        </tr>
        {% endfor %}
      </table>
    {% endfor %}
  </div>
</section>
<section class="">
  <div class="container">
    {% for item in results %}
      <h2>{{ item.item.get_category_display }} {{ item.item.name }} - Result by Students Rating</h2>
      <table class="table">
        <tr>
          <th>Code</th>
          <th>Student</th>
          <th>School</th>
          <th>Rank</th>
        </tr>
        {% for r in item.student_result %}
        <tr>
          <td>{{ r.result.participant.code }}</td>
          <td>{{ r.result.participant.student.user.get_full_name }}</td>
          <td>{{ r.result.participant.student.school }}</td>
          <td>{{ r.rank }}</td>
        </tr>
        {% endfor %}
      </table>
    {% endfor %}
  </div>
</section>
{% endblock %}

templates/item_rating_report.html
{% extends 'base.html' %}

{% block js %}
<script type="text/javascript">
$(document).ready(function(){
  var item = {{ item.id }}
  $(".confirm_result").click(function(){
    var self = this
    $.post(
      "/resultaction/",
      {'item':item,
      csrfmiddlewaretoken: '{{ csrf_token }}', action:'confirm' },
      function(data) {
        $(self).hide()
        $('.publish_result').show()
      });
  });
  $(".publish_result").click(function(){
    var self = this
    $.post(
      "/resultaction/",
      {'item':item,
      csrfmiddlewaretoken: '{{ csrf_token }}', action:'publish' },
      function(data) {
        $(self).hide()
        $('.reset_result').show()
        $('.label_published').show()
      });
  });
  $(".reset_result").click(function(){
    var self = this;
    $.post(
      "/resultaction/",
      {'item':item,
      csrfmiddlewaretoken: '{{ csrf_token }}', action:'reset' },
      function(data) {
        $(self).hide()
        $('.label_published').hide()
        $('.confirm_result').show()
      });
  });
});
</script>
{% endblock %}

{% block content %}
<section class="main" role="main">
<div class="container">
    <h2>{{ item.get_category_display }} {{ item.name }}</h2>
    <table class="table sortable">
        <tr>
            <th>Student</th>
            <th>Code</th>
            <th>Experts Rating</th>
            <th>Students Rating</th>
            <th>Total</th>
            {% for jury in item.jury_set.all %}
              <th>J{{ forloop.counter0|add:'1' }}</th>
            {% endfor %}
        </tr>
        {% for s in participants %}
        <tr>
            <td>{{ s.participant.student.user.get_full_name }}</td>
            <td>{{ s.participant.code }}</td>
            <td>{{ s.jury_mark }}</td>
            <td>{{ s.students_mark }}</td>
            <td>{{ s.total }}</td>
            {% for mark in s.jury_score %}
              {% if mark == '' %}
              <td>&nbsp;</td>
              {% else %}
              <td>{{ mark }}</td>
              {% endif %}
            {% endfor %}
        </tr>
        {% endfor %}
    </table>
    {% if item.is_result_published %}
    <button class="btn btn-danger reset_result">Reset Result</button>
    <button class="btn btn-success disabled btn-xs label_published" >Result Published</button>
    <button style="display:none;" class="btn btn-warning publish_result">Publish Result</button>
    <button style="display:none;" class="btn btn-primary confirm_result">Confirm Result</button>
    {% elif item.is_confirmed %}
    <button class="btn btn-warning publish_result">Publish Result</button>
    <button style="display:none;" class="btn btn-danger reset_result">Reset Result</button>
    <button style="display:none;" class="btn btn-success disabled btn-xs label_published">Result Published</button>
    <button style="display:none;" class="btn btn-primary confirm_result">Confirm Result</button>
    {% else %}
    <button class="btn btn-primary confirm_result">Confirm Result</button>
    <button style="display:none;" class="btn btn-danger reset_result">Reset Result</button>
    <button style="display:none;" class="btn btn-success disabled btn-xs label_published">Result Published</button>
    <button style="display:none;" class="btn btn-warning publish_result">Publish Result</button>
    {% endif %}
</div>
</section>
{% endblock %}

templates/item_report.html
{% extends 'base.html' %}
{% load url from future %}

{% block content %}
<section class="main" role="main">
<div class="container">
    <table class="table">
        <tr>
            <th>Item</th>
            <th>No. of Jurys</th>
            <th>No. of Participants</th>
        </tr>
        {% for item in items %}
        <tr>
            {% for group in user.groups.all %}
                {% if group.name == 'Jury' %}
                <td><a href="{% url 'item_jury_scoring' item.id %}">{{ item.get_category_display }} {{ item.name }}</a></td>
                {% endif %}
                {% if group.name == 'Admin' %}
                <td><a href="{% url 'item_rating_report' item.id %}">{{ item.get_category_display }} {{ item.name }}</a></td>
                {% endif %}
            {% endfor %}
            <td>{{ item.jury_set.count }}</td>
            <td>{{ item.participant_set.count }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
</section>
{% endblock %}

templates/item_scoring.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block content %}
<section class="main" role="main">
<div class="container">
    <h2>{{ item.get_category_display }} {{ item.name }}</h2>
    <form action='/score/save' method="post">
        <input type="hidden" value="{{item.id}}" name="item">
        {% csrf_token %}
        <table class="table">
            <tr>
                <th>Code</th>
                <th>Mark</th>
                <th>Out of 75</th>
            </tr>
            {% for participant in participants %}
            <tr>
                <td>#{{ participant.participant.code }}</td>
                {% if participant.score == 0 %}
                <td><input type="text" class="input" value="0" name="mark{{ participant.participant.code }}"></td>
                {% else %}
                <td><input type="text" class="input" value="{{ participant.score.mark }}" name="mark{{ participant.participant.code }}"></td>
                {% endif %}
                <td>{{ participant.outof75 }}</td>
            </tr>
            {% endfor %}
        </table>
        <input class="btn btn-primary" type="submit" value="Submit" name="upload_mark">
    </form>
</div>
</section>
{% endblock %}

templates/itemlist.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block css %}
<link rel="stylesheet" href="{% static 'jrating/jRating.jquery.css' %}" type="text/css" />
{% endblock %}

{% block js %}
<script type="text/javascript" src="{% static 'jrating/jRating.jquery.js' %}"></script>
<script type="text/javascript">
$(document).ready(function(){
    $(".rating.disabled").jRating({nbRates : 10,step: true, length: 10, rateMax:10, isDisabled:true});
    $(".rating.enabled").jRating({nbRates : 10,step: true, length: 10, rateMax:10});
    $(".confirm_rating").click(function(){
      $.post(
        "/rate/",
        {'action': 'confirm', csrfmiddlewaretoken: '{{ csrf_token }}'},
        function(data) {
          $(self).hide()
        });
      });
    });
</script>
{% endblock %}

{% block content %}

{% csrf_token %}
<section class="main" role="main">
  <div class="container">
    {% for item in items %}
    <h2>{{ item.item.get_category_display }} {{ item.item.name }}</h2>
    <div class="panel-group" id="accordion{{ item.item.id }}">
      {% for score in item.scores %}
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion{{ item.item.id }}" href="#collapse{{ score.participant.code }}"># {{ score.participant.code }} </a>
          </h4>
        </div>
        <div id="collapse{{ score.participant.code }}" class="panel-collapse collapse out">
          <div class="panel-body">
            {{ score.participant.student.user.get_full_name }}
            {% if item.item.is_confirmed or user.student.is_rating_confirmed %}
            <div class="rating disabled" data-average="{{ score.score }}" data-student="{{ score.participant.student.id }}" data-item="{{ item.item.id }}"></div>
            {% else %}
            <div class="rating enabled" data-average="{{ score.score }}" data-student="{{ score.participant.student.id }}" data-item="{{ item.item.id }}"></div>
            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endfor %}
    {% if not user.student.is_rating_confirmed %}
    <a class="btn btn-danger" href="{% url 'confirm_rating' %}">Confirm Rating</a>
    {% endif %}
  </div>
</section>
{% endblock %}

templates/password_change_done.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<section class="main" role="main">
<div class="container">
    <h1>{% trans 'Password change successful' %}</h1>
    <p>{% trans 'Your password was changed.' %}</p>
</div>
</section>
{% endblock %}

templates/password_change_form.html
{% extends "base.html" %}
{% load i18n static %}


{% block content %}
<section class="main" role="main">
<div class="container">
<div id="content-main">

<form action="" method="post">{% csrf_token %}
<div>
{% if form.errors %}
    <p class="errornote">
    {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
    </p>
{% endif %}

<h1>{% trans 'Password change' %}</h1>

<p>{% trans "Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly." %}</p>

<fieldset class="module aligned wide">

<div class="form-row">
    {{ form.old_password.errors }}
    <label for="id_old_password" class="required">{% trans 'Old password' %}:</label>{{ form.old_password }}
</div>

<div class="form-row">
    {{ form.new_password1.errors }}
    <label for="id_new_password1" class="required">{% trans 'New password' %}:</label>{{ form.new_password1 }}
</div>

<div class="form-row">
{{ form.new_password2.errors }}
    <label for="id_new_password2" class="required">{% trans 'Password (again)' %}:</label>{{ form.new_password2 }}
</div>

</fieldset>

<div class="submit-row">
    <input type="submit" class="btn btn-primary" value="{% trans 'Change my password' %}" class="default" />
</div>

<script type="text/javascript">document.getElementById("id_old_password").focus();</script>
</div>
</form></div>

</div>
</section>
{% endblock %}

templates/special_awards.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block content %}
<section class="main" role="main">
  <div class="container">
    {% for a in awards %}
    <div class="alert alert-info"><h4>{{ a.title }}</h4>
        <p>{{ a.participant.student.user.get_full_name }}</p>
        <p>Item : {{ a.participant.item }}</p>
        <p>code : #{{ a.participant.code }}</p>
    </div>
    {% endfor %}
  </div>
</section>
{% endblock %}